// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc4mPEHg_ev6rEXoA3qcQWkehNE7nWKvc',
    appId: '1:913467711681:web:3e1e039750e52d2ba9b440',
    messagingSenderId: '913467711681',
    projectId: 'flutter-1400d',
    authDomain: 'flutter-1400d.firebaseapp.com',
    storageBucket: 'flutter-1400d.appspot.com',
    measurementId: 'G-HMEG9LZ3TW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0OraNu4Yz5X2hIpK2PlLiyBsEbol3Pv0',
    appId: '1:913467711681:android:5b845e3ae3101c9fa9b440',
    messagingSenderId: '913467711681',
    projectId: 'flutter-1400d',
    storageBucket: 'flutter-1400d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCdSzlMxznmm4NkkliFIM7HZ7Eu5xInyw',
    appId: '1:913467711681:ios:6feec7889567ea93a9b440',
    messagingSenderId: '913467711681',
    projectId: 'flutter-1400d',
    storageBucket: 'flutter-1400d.appspot.com',
    iosClientId: '913467711681-g96a5abg9kf3pjmamq5o4uc16kflipee.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc4mPEHg_ev6rEXoA3qcQWkehNE7nWKvc',
    appId: '1:913467711681:web:9f0bf26f127a6b13a9b440',
    messagingSenderId: '913467711681',
    projectId: 'flutter-1400d',
    authDomain: 'flutter-1400d.firebaseapp.com',
    storageBucket: 'flutter-1400d.appspot.com',
    measurementId: 'G-7NFD60QGEN',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDc4mPEHg_ev6rEXoA3qcQWkehNE7nWKvc',
    appId: '1:913467711681:web:cab905cae91479e8a9b440',
    messagingSenderId: '913467711681',
    projectId: 'flutter-1400d',
    authDomain: 'flutter-1400d.firebaseapp.com',
    storageBucket: 'flutter-1400d.appspot.com',
    measurementId: 'G-W1VVG52MS6',
  );
}
