name: ytp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.0-142.0.dev


dependencies:
  flutter:
    sdk: flutter


# PACKAGES
  cupertino_icons: ^1.0.8
# routes
  auto_route: ^8.3.0
# ui
  flutter_staggered_grid_view: ^0.7.0
# state management
  provider: ^6.1.2
# shared preferences
  shared_preferences: ^2.3.0
# For text fonts
  google_fonts: ^6.2.1
# For images
  image_picker: ^1.1.2
  photo_manager: ^3.2.2
  permission_handler: ^11.3.1
  photo_manager_image_provider: ^2.1.1
  transparent_image: ^2.0.1
  camera: ^0.11.0+1
  flutter_svg: ^2.0.10+1
  flutter_native_splash: ^2.4.1




 



  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  auto_route_generator: ^8.1.0
  build_runner:

flutter:

  uses-material-design: true

  assets:
    - assets/jpg/
    - assets/png/
    - assets/svg/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
